version: '3'

services:
  pg_database:
    image: postgres:14-alpine
    container_name: pg_database
    environment:
      - POSTGRES_DB=Library
      - POSTGRES_USER=Powergleb
      - POSTGRES_PASSWORD=1234
    ports:
      - "5435:5432"